deployments:
  environmentMapping:
    development:
      - "dev*"
      - "Entwicklung"
      - "desenvolvimento"
      - "дев"
    testing:
      - "testes"
      - "Test"
      - "TST-*"
      - "тест"
    staging:
      - "Pre-Prod"
      - "STG-*"
      - "staging"
    production:
      - "Produktion"
      - "produção"
      - "продакшн"
      - "PROD-*"
  deploymentGating:
    enabled: true # to enable the feature
    retry: 50 # run poll action 50 times
    sleep: 30 # wait 30 seconds between each poll
    environments: # select the environments you'd like to use with this feature
      - Development
      - Production
  environments: # select the environments you'd like to use with this feature
    - Development
    - Production
  services:
    ids:
      - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzViMzA4NTg3LTA1ODUtNGIyZS1iMWVmLTEyNzI1NjFiMGQ0ZC9kMzdiYzFiYS03NTAzLTExZjEtODU5MS0wYWZmY2YwZmJkMDk=
      
